Update tag_residential_loadshifting_assets.yaml
openENTRANCE/openentrance pull request #192
Opened 2022-06-02 08:12 UTC by ryan-oreilly

Add Electric Vehicle_55 which represents expectations for EV energy demand using the Fit for 55 scenario

2022-06-09 14:11 UTC, sandrinecharousset requested changes

2022-06-10 08:18 UTC, danielhuppmann commented on definitions/variable/tag_residential_loadshifting_assets.yaml
> +   - Electric Vehicle_55:
Yes, I agree - this is not the intended usage of a variable. Please remove or close this PR and start a new one that has only the changes to the other descriptions.

2022-06-16 16:56 UTC, sandrinecharousset commented on definitions/variable/tag_residential_loadshifting_assets.yaml
> +   - Electric Vehicle_55:
@ryan-oreilly

2022-06-23 09:29 UTC, sandrinecharousset commented on definitions/variable/tag_residential_loadshifting_assets.yaml
> +      description: electric vehicles using Fit for 55 scenario
```suggestion
    
```

2022-06-23 09:30 UTC, sandrinecharousset requested changes
suggestion to remove electric vehicle_55

2022-06-23 09:30 UTC, sandrinecharousset commented on definitions/variable/tag_residential_loadshifting_assets.yaml
> +   - Electric Vehicle_55:
```suggestion
   
```

2022-06-24 08:15 UTC, sandrinecharousset approved these changes

2022-06-25 15:55 UTC, merged