Add capacity vars
openENTRANCE/openentrance pull request #324
Opened 2024-01-24 12:14 UTC by robertpietzcker

2024-01-24 12:14 UTC, robertpietzcker commented
(I didn't know how to repeat the checks after updating the indentation, so I did a new PR)

2024-01-26 05:37 UTC, danielhuppmann requested changes
One typo, two minor edits in the description to improve readability.

2024-01-26 05:37 UTC, danielhuppmann commented on definitions/variable/technology/technologies.yaml
> +    description: Total installed (available) capacity of hydrogen to liquids (synguel) plants
```suggestion
    description: Total installed (available) capacity of hydrogen-to-liquids (synfuel) plants
```

2024-01-26 05:37 UTC, danielhuppmann commented on definitions/variable/technology/technologies.yaml
> +    description: Total installed (available) capacity of hydrogen to methane (syngas) plants
```suggestion
    description: Total installed (available) capacity of hydrogen-to-methane (syngas) plants
```

2024-01-26 08:02 UTC, robertpietzcker commented
thanks, @danielhuppmann !

2024-01-26 08:29 UTC, danielhuppmann approved these changes
Thanks!

2024-01-26 08:30 UTC, merged