Add definitions and mappings for REMIND 3.2
openENTRANCE/openentrance pull request #326
Opened 2024-02-08 17:22 UTC by danielhuppmann

2024-02-08 18:00 UTC, phackstock commented
Ah that's different to iamconsortium/nomenclature#319 though. This one's failing because I cleaned up the CLI and adjusted it to the standard of giving multiple input values.
From:
```console
nomenclature validate-project . --dimensions "['region', 'scenario', 'variable']"
```
you'll now have to do:
```console
nomenclature validate-project . --dimensions region --dimensions scenario --dimensions variable
```

Reason for the change was that the first solution was a custom one from us, the current one adheres to the standards of CLI programs. I could think about offering a shorthand `-d` to make the command shorter.

2024-02-08 18:55 UTC, robertpietzcker commented
I am sorry, I didn't think before when replying to the email...
is this supposed to be a different REMIND version than the one Renato used before? I think not, or do you disagree, @Renato-Rodrigues  ?

2024-02-09 06:56 UTC, danielhuppmann commented
> is this supposed to be a different REMIND version than the one Renato used before?

No scenarios were submitted to the ECEMF-internal Scenario Explorer from REMIND 3.2 yet. This PR is just a fix such that native-region-names are "REMIND 3.2|..." instead of "REMIND 3.0|...". The mapping assumes the 21-region-version of REMIND, simplifying the mappings.

Please review that my allocation of the non-EU European countries to the iso3_codes-attribute are correct - I copied them from the REMIND 3.1 definitions at https://github.com/IAMconsortium/common-definitions/blob/main/definitions/region/native_regions/REMIND_3.1.yml.

I also noticed that REMIND submits already-aggregated for "EU27" in some project - are you also planning to do this for REMIND 3.2 in the ecemf-internal instance?

2024-02-09 09:25 UTC, Renato-Rodrigues commented
> No scenarios were submitted to the ECEMF-internal Scenario Explorer from REMIND 3.2 yet.

There was no change in the regions definitions from REMIND 3.0 to REMIND 3.1 or REMIND 3.2. 
Therefore, a few 3.2 results were already uploaded using the previous mapping.
So my question is why did you not copied directly the below mapping? 
https://github.com/IAMconsortium/common-definitions/blob/main/mappings/REMIND_3.1.yml

> The mapping assumes the 21-region-version of REMIND, simplifying the mappings.

REMIND results can be uploaded in both 12-regions and 21-regions configurations, so I would not remove the support to the 12 regions (EUR and NEU).

> Please review that my allocation of the non-EU European countries to the iso3_codes-attribute are correct

They should be correct, but I will double check them soon.

> I also noticed that REMIND submits already-aggregated for "EU27" in some project - are you also planning to do this for REMIND 3.2 in the ecemf-internal instance?

Yes, we handle ourselves our EU27 regions aggregations and upload them directly.

One last point, any special reason why you removed the support for the R5 and R10 automatic aggregation of AR6 regions from the 3.1 common-definitions mapping?

2024-02-09 09:43 UTC, danielhuppmann commented
Note that ECEMF does not use R9 and R10 region definitions (yet?), that's why I started from https://github.com/openENTRANCE/openentrance/blob/main/mappings/remind_3.0.yaml, not the mapping in common-definitions. In turn, the common-definitions repository does not have the INNOPATHS mappings...

Also, no results using REMIND 3.2 were yet submitted to the ecemf-internal database (Simon Moreno tried yesterday but failed, this PR is fixing the registration so that he can proceed).

2024-02-09 14:58 UTC, Renato-Rodrigues requested changes

2024-02-09 14:58 UTC, Renato-Rodrigues commented on mappings/REMIND_3.2.yml
> +  - DEU: REMIND 3.2|Germany
```suggestion
    # 12-region version of REMIND
  - EUR: REMIND 3.2|EU 28
  - NEU: REMIND 3.2|Non-EU28 Europe
  # 21-region version of REMIND
  - DEU: REMIND 3.2|Germany
```

2024-02-09 14:58 UTC, Renato-Rodrigues commented on mappings/REMIND_3.2.yml
> +    - DEU
```suggestion
    # 12-region version of REMIND
    - EUR
    - NEU
    # 21-region version of REMIND
    - DEU
```

2024-02-09 14:58 UTC, Renato-Rodrigues commented on mappings/REMIND_3.2.yml
> +    - DEU
```suggestion
    # 12-region version of REMIND
    - EUR
    - NEU
    # 21-region version of REMIND
    - DEU
```

2024-02-09 14:58 UTC, Renato-Rodrigues commented on mappings/REMIND_3.2.yml
> +    - DEU
```suggestion
    # 12-region version of REMIND
    - EUR
    # 21-region version of REMIND
    - DEU
```

2024-02-09 14:58 UTC, Renato-Rodrigues commented on mappings/REMIND_3.2.yml
> +    - DEU
```suggestion
    # 12-region version of REMIND
    - EUR
    # 21-region version of REMIND
    - DEU
```

2024-02-09 15:02 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_3.2.yaml
> +  - REMIND 3.2|Germany:
```suggestion
# 12-region version of REMIND
  - REMIND 3.2|EU 28:
      iso3_codes: [ALA, AUT, BEL, BGR, CYP, CZE, DNK, ESP, EST, FIN, FRO, GGY, GIB,
        GRC, HRV, HUN, IMN, IRL, ITA, JEY, LTU, LUX, LVA, MLT, NLD, POL, PRT, ROU,
        SVK, SVN, SWE, FRA, DEU, ITA, GIB, GGY, GBR]
  - REMIND 3.2|Non-EU28 Europe:
      iso3_codes: [ALB, AND, BIH, CHE, GRL, ISL, LIE, MCO, MKD, MNE, NOR, SJM, SMR,
        SRB, TUR, VAT]
# 21-region version of REMIND
  - REMIND 3.2|Germany:
```

2024-02-09 15:06 UTC, Renato-Rodrigues approved these changes

2024-02-09 15:07 UTC, merged

2024-02-09 15:07 UTC, danielhuppmann commented
Permissions added for the REMIND team to submit scenarios for REMIND 3.2 to the ECEMF-internal Scenario Explorer